srmsproject/srms_win1/mysite/modules/userinfo/urls.py
# coding=utf-8

from django.conf.urls import url
from modules.userinfo import views

urlpatterns = [
    url(r'login/$', views.user_login, name='userinfo_login'),
    # url(r'login/$', views.UserinfoList.as_view(), name="userinfo_list"),
    url(r'logout/$', views.user_logout, name='userinfo_logout'),
    url(r'^stafflist/', views.UserinfoList.as_view(), name="userinfo_list"),
    # url(r'^login/', views.UserinfoLogin.as_view(), name="userinfo_login"),
    # url(r'^logout/', views.UserinfoLogout.as_view(), name="userinfo_logout"),
    url(r'^list/', views.UserinfoList.as_view(), name="userinfo_list"),
    url(r'^add/', views.UserinfoCreate.as_view(), name="userinfo_add"),
    url(r'(?P<pk>[0-9]+)/edit$', views.UserinfoUpdate.as_view(), name="userinfo_edit"),
    # url(r'(?P<pk>[0-9]+)/delete$', views.UserinfoDelete.as_view(), name="userinfo_delete"),
    # url(r'^batchdelete/', views.UserinfoBatchDelete.as_view(), name="userinfo_batch_delete"),
    url(r'^homepage/', views.UserinfoHomepage.as_view(), name="userinfo_homepage"),
]

srmsproject/srms_win1/mysite/mysite/urls.py
# coding=utf-8
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.static import serve
from django.http import HttpResponseRedirect,HttpRequest,HttpResponse
from django.contrib import admin

from mysite import settings
from modules.common.views import SidebarMenusList


handler500 = "modules.common.views.redirect_500_error"
handler404 = "modules.common..views.redirect_404_error"
handler403 = "modules.common..views.redirect_403_error"
handler400 = "modules.common..views.redirect_400_error"


def index(request):
    response = HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
    # response = HttpResponse('/')
    return response


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', admin.site.urls),
    url(r'^$', index),
    url(r'^homepage/', include('modules.common.urls', namespace='homepage')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_PATH, }),
    url(r'^contentinfo/', include('modules.contentinfo.urls', namespace='contentinfo')),
    url(r'^serverinfo/', include('modules.serverinfo.urls', namespace='serverinfo')),
    url(r'^userinfo/', include('modules.userinfo.urls', namespace='userinfo')),
    url(r'^userlog/', include('modules.userlog.urls', namespace='userlog')),
    url(r'^systeminfo/', include('modules.systeminfo.urls', namespace='systeminfo')),
    url(r'^getmenubyuser/$', SidebarMenusList.as_view(), name='getmenubyuser'),
]


# 上传文件目录
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srmsproject/srms_win1/mysite/modules/homepage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

srmsproject/srms_win1/mysite/modules/userinfo/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin
import traceback
from django.db.models import Q


class ProfileBase(type):  # 对于传统类，他们的元类都是types.ClassType
    def __new__(cls, name, bases, attrs):  # 带参数的构造器，__new__一般用于设置不变数据类型的子类
        module = attrs.pop('__module__')
        parents = [b for b in bases if isinstance(b, ProfileBase)]
        if parents:
            fields = []
            for obj_name, obj in attrs.items():
                if isinstance(obj, models.Field): fields.append(obj_name)
                User.add_to_class(obj_name, obj)
            UserAdmin.fieldsets = list(UserAdmin.fieldsets)
            UserAdmin.fieldsets.append((name, {'fields': fields}))
        return super(ProfileBase, cls).__new__(cls, name, bases, attrs)


class ProfileUser(object):
    __metaclass__ = ProfileBase  # 类属性


GENDER_CHOICES = (
    ('M', u'男'),
    ('F', u'女'),
)


class Userinfo(ProfileUser):
    """管理员扩展信息"""
    gender = models.CharField(u"性别", max_length=2, choices=GENDER_CHOICES, blank=True)
    mobile_phone = models.CharField(u"电话", max_length=11, blank=True)
    photo = models.ImageField(u"头像", upload_to='avatars', default='avatars/user.jpg', blank=True)
    remark1 = models.CharField(u"备注1", max_length=256, blank=True)
    remark2 = models.CharField(u"备注2", max_length=256, blank=True)
    writetime = models.CharField(u"更新时间", max_length=100)
    USERNAME_FIELD = 'username'
    FIRST_NAME_FIELD = 'first_name'


    class Meta:
        verbose_name = u"用户信息"
        ordering = ['-id']  # id倒叙

srmsproject/srms_win1/mysite/modules/homepage/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

srmsproject/srms_win1/mysite/modules/userinfo/views.py
# coding=utf-8

import traceback
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth import authenticate, login, logout
from django.utils.http import is_safe_url
from django.shortcuts import resolve_url
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from django.contrib import messages
from django.contrib.auth.hashers import make_password, check_password
from mysite import settings
import datetime


class UserinfoList(ListView):
    context_object_name = "userinfo_list"
    template_name = "userinfo_list.html"
    allow_empty = True
    paginate_by = 10

    def get_queryset(self):
        return User.objects.all()


class UserinfoCreate(SuccessMessageMixin, CreateView):
    template_name = "userinfo_edit.html"
    success_url = "/userinfo/list"
    model = User
    fields = ["username", "password", "is_superuser", "is_staff", "email", "gender", "mobile_phone", "photo", "remark1",
              "remark2"]
    success_message = u"%(username)s 成功创建"


    def get_context_data(self, **kwargs):
        context = super(UserinfoCreate, self).get_context_data(**kwargs)
        context["form_content"] = u"新增用户"
        return context

    # 对新增用户密码做加密处理
    def form_valid(self, form):
        form.instance.password = make_password(form.instance.password)
        return super(UserinfoCreate, self).form_valid(form)


class UserinfoUpdate(SuccessMessageMixin, UpdateView):
    template_name = "userinfo_edit.html"
    success_url = "/userinfo/list"
    model = User
    fields = ["username", "password", "is_superuser", "is_staff", "email", "gender", "mobile_phone", "photo", "remark1",
              "remark2"]
    success_message = u"%(username)s 修改成功"

    def get_object(self):
        object = super(UserinfoUpdate, self).get_object()
        return object

    def get_context_data(self, **kwargs):
        context = super(UserinfoUpdate, self).get_context_data(**kwargs)
        context["form_content"] = u"编辑用户信息"
        return context

    # 对编辑用户密码做加密处理
    def form_valid(self, form):
        if form.instance.password != self.get_object().password:
            form.instance.password = make_password(form.instance.password)
        return super(UserinfoUpdate, self).form_valid(form)


class UserinfoDelete(SuccessMessageMixin, DeleteView):
    template_name = "base/confirm_delete.html"
    success_url = "/userinfo/list"
    model = User
    fields = "__all__"
    success_message = u"%(name)s 删除成功"


class UserinfoLogin(View):
    username, password = "", ""

    def get(self, request, *args, **kwargs):
        try:
            template_name = "login.html"
            return render_to_response(template_name, {})
        except:
            traceback.print_exc()

    def post(self, request, *args, **kwargs):
        remember_me = request.POST.get('remember_me', 0)
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        redirect_to = settings.LOGIN_REDIRECT_URL
        user = authenticate(username=username, password=password)
        print "login user==", user
        if user:
            print "is_staff==", user.is_staff
            print "is_active==", user.is_active
        if user and user.is_staff and user.is_active:
            # 确保用户始发重定向的网址是安全的。.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
            # Okay, 安全检查完成，登录用户。
            else:
                login(request, user)
                # 检查是否保存
                if not remember_me:  # 默认14天后登陆超时
                    expiry_time = 1 * 24 * 3600  # 24小时后登陆超时
                    request.session.set_expiry(expiry_time)

            return HttpResponseRedirect(redirect_to)
        elif user and not user.is_staff:
            messages.warning(request, u"您没有登录权限")
        elif user and not user.is_active:
            messages.warning(request, u"您已经离职，无登录权限")
        else:
            messages.warning(request, u"用户名或密码不正确")


class UserinfoLogout(View):
    def get(self, request, *args, **kwargs):
        try:
            template_name = "login.html"
            return render_to_response(template_name, {})
        except:
            traceback.print_exc()
            return redirect(reverse('userinfo:userinfo_login'))

    def post(self, request, *args, **kwargs):
        try:
            return HttpResponse({})
        except:
            traceback.print_exc()


@sensitive_post_parameters()
@csrf_protect
@never_cache
def user_login(request, template_name='login.html', redirect_field_name=REDIRECT_FIELD_NAME,current_app=None):
    """显示登录表单和处理登录动作
    :param request:请求对象
    :param template_name:返回模板的名字
    :param redirect_field_name:重定向字段名
    :param current_app:当前应用程序
    :return:
    """

    redirect_to = request.GET.get(redirect_field_name, "/userinfo/list")
    remember_me = request.POST.get('remember_me', 0)
    username, password = "", ""

    if request.user.is_authenticated:
        return HttpResponseRedirect(redirect_to)

    now = datetime.datetime.now()
    closedate = datetime.datetime(int(settings.CLOSE_DATE[0:4]), int(settings.CLOSE_DATE[4:6]),
                                  int(settings.CLOSE_DATE[6:8]))
    if closedate < now:
        messages.warning(request, u"系统已经超过授权使用时间！")
        return TemplateResponse(request, template_name, {})

    if request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")

        user = authenticate(username=username, password=password)
        print "login user==", user
        if user:
            print "is_staff==", user.is_staff
            print "is_active==", user.is_active
        if user and user.is_staff and user.is_active:
            # 确保用户始发重定向的网址是安全的。.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
                # return HttpResponse('userinfo_list.html')
            # Okay, 安全检查完成，登录用户。
            else:
                login(request, user)
                # 检查是否保存
                # if not remember_me:  # 默认14天后登陆超时
                #     expiry_time = 1 * 24 * 3600  # 24小时后登陆超时
                #     request.session.set_expiry(expiry_time)

            return HttpResponseRedirect(redirect_to)
        # elif user and not user.is_staff:
        #     login(request, user)
        #     return HttpResponseRedirect("/contentinfo/user/")
        #     # messages.warning(request, u"您没有登录权限")
        elif user and not user.is_active:
            messages.warning(request, u"您已经离职，无登录权限")
        else:
            messages.warning(request, u"用户名或密码不正确")

    current_site = get_current_site(request)

    context = {
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
        "username": username,
        "password": password,
    }

    if current_app:
        request.current_app = current_app
    return TemplateResponse(request, template_name, context)
    # return HttpResponseRedirect("userinfo_list.html")

def user_logout(request):
    def go_back():
        redirect_to = "/userinfo/login"
        return HttpResponseRedirect(redirect_to)

    logout(request)
    return go_back()


class UserinfoHomepage(View):
    def get(self, request, *args, **kwargs):
        try:
            template_name = "homepage.html"
            return render_to_response(template_name, {"request": request})
        except:
            traceback.print_exc()
            return redirect(reverse('userinfo:userinfo_list'))

    def post(self, request, *args, **kwargs):
        try:
            return HttpResponse({})
        except:
            traceback.print_exc()

srmsproject/srms_win1/mysite/modules/userinfo/templates/homepage.html
{% extends "base/base.html" %}

{% block page-content %}
<div class="row">
<div class="col-xs-12">
    <div id="home" class="tab-pane in active">
        <div class="row">
            <div class="col-xs-12 col-sm-3 center">
                <span class="profile-picture">
                    <img class="editable img-responsive" {% if request.user.photo %} src="{{ request.user.photo.url }}" alt="{{ request.user.username }}" {% else %}  src="/media/avatars/user.jpg" alt="{{ request.user.username }}" {% endif %} />
                </span>

                <div class="space space-4"></div>

                <a href="#" class="btn btn-sm btn-block btn-success">
                    <i class="ace-icon fa fa-plus-circle bigger-120"></i>
                    <span class="bigger-110">添加好友</span>
                </a>

                <a href="#" class="btn btn-sm btn-block btn-primary">
                    <i class="ace-icon fa fa-envelope-o bigger-110"></i>
                    <span class="bigger-110">发送消息</span>
                </a>
            </div><!-- /.col -->

            <div class="col-xs-12 col-sm-9">


                <div class="profile-user-info">
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 用户名 </div>

                        <div class="profile-info-value">
                            <span>{{ request.user.username }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 电话 </div>

                        <div class="profile-info-value">
                            <span>{{ request.user.mobile_phone }}</span>
                        </div>
                    </div>

                    <div class="profile-info-row">
                        <div class="profile-info-name"> 邮箱 </div>

                        <div class="profile-info-value">
                            <span>{{ request.user.email }}</span>
                        </div>
                    </div>

                    <div class="profile-info-row">
                        <div class="profile-info-name"> 加入系统 </div>

                        <div class="profile-info-value">
                            <span>{{ request.user.date_joined }}</span>
                        </div>
                    </div>

                    <div class="profile-info-row">
                        <div class="profile-info-name"> 上次登录 </div>

                        <div class="profile-info-value">
                            <span>{{ request.user.last_login }}</span>
                        </div>
                    </div>

                </div>

                <div class="hr hr-8 dotted"></div>


            </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="space-20"></div>



    </div><!-- /#home -->

</div>
</div><!-- /.row -->





{% endblock %}

srmsproject/srms_win1/mysite/modules/userinfo/templates/userinfo_edit.html
{% extends "base/base_edit.html" %}



{% block modules_js %}
    <script type="text/javascript">
        $("#id_password").attr("type","password");

        f = $(".form-horizontal").get(0);
        $(f).validate({rules: {id_mobile_phone: {digits: true},id_email: {email: true}}});


    </script>
{% endblock %}

srmsproject/srms_win1/mysite/modules/userinfo/templates/userinfo_list.html
{% extends "base/base.html" %}
{％ load i18n ％}
{％ load userinfo_tags ％}

{% block breadcrumb %}
    <li class="active">用户列表</li>
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="page-header">
                <div class="widget-box widget-color-blue2">
                    <div class="widget-header">
                        <i class="menu-icon fa fa-filter"></i>
                        <h5 class="widget-title">查询用户</h5>

                        <div class="widget-toolbar">
                            <a href="#" data-action="collapse">
                                <i class="ace-icon fa fa-chevron-up"></i>
                            </a>
                        </div>

                        <div class="widget-toolbar">
                            <button class="btn btn-xs btn-info" onclick="$('#user_form').submit()" data-rel="tooltip"
                                    title="搜索资源">
                                <i class="ace-icon glyphicon glyphicon-search bigger-120"></i>
                                搜索
                            </button>
                            <button class="btn btn-xs btn-info" data-rel="tooltip" title="新增用户"
                                    onclick="window.location.href='{% url "userinfo:userinfo_add" %}'">
                                <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                                新增
                            </button>
                        </div>
                    </div>
                    <div class="widget-body">
                        <form id="user_form" class="form-horizontal" method="get">
                            <div class="widget-main padding-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <p>
                                            <input type="text" id="dept_name" name="dept_name" placeholder="归属服务器搜索"
                                                   onclick="query_dept_param()" value="{{ dept_name }}" readonly/>
                                            <input type="hidden" id="dept_ids" name="dept_ids" value="{{ dept_ids }}"/>
                                            <input type="text" id="name" name="name" placeholder="名称搜索"
                                                   value="{{ first_name }}"/>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <div class="table-responsive">

                <table class="table table-striped table-hover dataTable">
                    <thead>
                    <tr>
                        <th class="center">
                            <label class="pos-rel">
                                <input type="checkbox" class="ace" name="check_all"/>
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th class="center">用户编号</th>
                        <th class="center">用户名称</th>
                        <th class="center">超级用户</th>
                        <th class="center">职员状态</th>
                        <th class="center">性别</th>
                        <th class="center">邮箱</th>
                        <th class="center">电话</th>
                        <th class="center">备注</th>
                        <th class="center">更新时间</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for userinfo in userinfo_list %}
                        <tr class="center">
                            <td>
                                <label class="pos-rel">
                                    <input type="checkbox" class="ace" name="db_id" value="{{ userinfo.id }}"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>

                            <td>{{ userinfo.id }}</td>
                            <td>{{ userinfo.username }}</td>
                            <td>{{ userinfo.is_superuser|yesno:"是,否,"  }}</td>
                            <td>{{ userinfo.is_staff|yesno:"是,否," }}</td>
                            <td>{{ userinfo.get_gender_display }}</td>
                            <td>{{ userinfo.email }}</td>
                            <td>{{ userinfo.mobile_phone }}</td>
                            <td>{{ userinfo.remark1 }}</td>
                            <td>{{ userinfo.writetime }}</td>
                            <td>

                                <div>
                                    <button class="btn btn-minier btn-info"
                                            onclick="window.location.href='{% url "userinfo:userinfo_edit" pk=userinfo.id %}'">
                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                    </button>
                                    <button class="btn btn-minier btn-danger"
                                            onclick="window.location.href=''">
                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                    </button>

                                </div>

                            </td>
                        </tr>
                    {% empty %}
                        <tr class="info">
                            <td colspan="25">抱歉，目前没有满足条件的用户信息。</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.span -->
        </div>
    </div><!-- /.row -->

    {% include  "base/paginator.html" %}

{% endblock %}