srmsproject/srms_win/mysite/modules/serverinfo/urls.py
# coding=utf-8

from django.conf.urls import url
from modules.serverinfo import views

urlpatterns = [

    url(r'^contentset/list/', views.ContentSetList.as_view(), name="contentset_list"),
    url(r'^contentset/add/', views.ContentSetCreate.as_view(), name="contentset_add"),
    url(r'^contentset/(?P<pk>[0-9]+)/edit/', views.ContentSetUpdate.as_view(), name="contentset_edit"),
    url(r'^contentset/(?P<pk>[0-9]+)/delete/', views.ContentSetDelete.as_view(), name="contentset_delete"),
    url(r'(?P<pk>[0-9]+)/initpath/', views.ServerinfoInitPath.as_view(), name="serverinfo_initpath"),
    url(r'(?P<pk>[0-9]+)/init', views.ServerinfoInit.as_view(), name="serverinfo_init"),
    url(r'(?P<pk>[0-9]+)/sync/', views.ServerinfoSyncContent.as_view(), name="serverinfo_sync"),
    url(r'(?P<pk>[0-9]+)/conn/', views.ServerinfoConn.as_view(), name="serverinfo_conn"),
    url(r'^list/', views.ServerinfoList.as_view(), name="serverinfo_list"),
    url(r'^add/', views.ServerinfoCreate.as_view(), name="serverinfo_add"),
    url(r'(?P<pk>[0-9]+)/edit/', views.ServerinfoUpdate.as_view(), name="serverinfo_edit"),
    url(r'(?P<pk>[0-9]+)/delete/', views.ServerinfoDelete.as_view(), name="serverinfo_delete"),
    # url(r'^batchdelete/', views.ServerinfoBatchDelete.as_view(), name="serverinfo_batch_delete"),
    url(r'^chart/', views.ServerinfoChart.as_view(), name="serverinfo_chart"),

]

srmsproject/srms_win/mysite/mysite/urls.py
# coding=utf-8
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.static import serve
from django.http import HttpResponseRedirect
from django.contrib import admin

from mysite import settings
from modules.common.views import SidebarMenusList


handler500 = "modules.common.views.redirect_500_error"
handler404 = "modules.common..views.redirect_404_error"
handler403 = "modules.common..views.redirect_403_error"
handler400 = "modules.common..views.redirect_400_error"


def index(request):
    response = HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
    return response


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', admin.site.urls),
    url(r'^$', index),
    url(r'^homepage/', include('modules.common.urls', namespace='homepage')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_PATH, }),
    url(r'^contentinfo/', include('modules.contentinfo.urls', namespace='contentinfo')),
    url(r'^serverinfo/', include('modules.serverinfo.urls', namespace='serverinfo')),
    url(r'^userinfo/', include('modules.userinfo.urls', namespace='userinfo')),
    url(r'^userlog/', include('modules.userlog.urls', namespace='userlog')),
    url(r'^systeminfo/', include('modules.systeminfo.urls', namespace='systeminfo')),
    url(r'^getmenubyuser/$', SidebarMenusList.as_view(), name='getmenubyuser'),
]


# 上传文件目录
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srmsproject/srms_win/mysite/modules/serverinfo/models.py
# coding=utf-8

from __future__ import unicode_literals
from stat import *
import datetime
import traceback
from django.db import models
import paramiko
from django.utils import timezone
from django.contrib.auth.models import User

remotepathlist = []

CHECK_CHOICES = (
    ('0', u'否'),
    ('1', u'是'),
)


class Serverinfo(models.Model):
    """服务器信息"""
    name = models.CharField(u"服务器名称", max_length=100)
    ip = models.CharField(u"IP", max_length=100)
    port = models.CharField(u"端口", max_length=100)
    username = models.CharField(u"用户名称", max_length=100)
    password = models.CharField(u"用户密码", max_length=100)
    checkflag = models.CharField(u"是否监控", max_length=2, choices=CHECK_CHOICES, blank=True)#0 代表不监控；1 代表监控；
    writetime = models.DateTimeField(u"更新时间", null=True, blank=True, default=datetime.datetime.now)
    synctime = models.DateTimeField(u"同步时间", null=True, blank=True)
    sftp = None

    # 连接远程主机
    def connect(self):
        if self.sftp:
            return self.sftp
        try:
            host = paramiko.Transport((self.ip, int(self.port)))
            host.connect(username=self.username, password=self.password)  # 登录远程服务器
            self.sftp = paramiko.SFTPClient.from_transport(host)   # sftp传输协议
        except:
            traceback.print_exc()
        return self.sftp

    # 获取服务器目录的所有目录和文件属性
    def getDirContent(self, dir):
        sftp = self.connect()
        listdir = []
        if sftp:
            listdir = sftp.listdir_attr(dir)
        return listdir


    # 初始化服务器根目录的所有目录和文件属性
    def initContent(self):
        from modules.contentinfo.models import Contentinfo

        filelist = self.getDirContent(r"/")
        for f in filelist:
            if S_ISDIR(f.st_mode):
                ftype = 1
            else:
                ftype = 2
            try:
                content = Contentinfo.objects.get(absname="/" + f.filename, serverid=self)
            except:
                content = None
            if content:
                content.writetime = datetime.datetime.now()
                content.save()
            else:
                content = Contentinfo(name=f.filename, absname="/" + f.filename, ftype=ftype, superid="/",
                                      serverid=self,
                                      changeflag=0,
                                      oldproperty="",
                                      newproperty="", checkflag=0, writetime=datetime.datetime.now())
                content.save()
        return []

    # 初始化服务器指定目录的所有目录
    def initPathContent(self, remotepath):
        from modules.contentinfo.models import Contentinfo

        filelist = []
        count = remotepath.count("/")
        for l in range(count):
            dirdict = {}
            i = remotepath.rfind("/")
            if i == 0:
                dirdict["superid"] = "/"
            else:
                dirdict["superid"] = remotepath[:i]
            dirdict["name"] = remotepath[i + 1:]
            dirdict["absname"] = remotepath
            remotepath = remotepath[:i]
            filelist.append(dirdict)
        for file in filelist:
            try:
                content = Contentinfo.objects.get(absname=file["absname"], serverid=self)
            except:
                content = None
            if not content:
                content = Contentinfo(name=file["name"], absname=file["absname"], ftype=1,
                                      superid=file["superid"],
                                      serverid=self, changeflag=0,
                                      oldproperty="",
                                      newproperty="", checkflag=0, writetime=datetime.datetime.now())
                content.save()

        return "initPathContent==============="

    # 将指定目录下的所有目录和文件格式化为list
    def formatRemotepath(self, remotepath):
        #获取目录下的所有目录和文件属性
        if self.connect():
            contents = self.connect().listdir_attr(remotepath)
        else:
            contents = []

        #循环处理所有目录和文件放到dirlist列表中
        for content in contents:
            temp_contentdict = {}
            if S_ISDIR(content.st_mode):
                temp_contentdict["name"] = content.filename
                temp_contentdict["absname"] = remotepath + "/" + content.filename
                temp_contentdict["ftype"] = 1
                temp_contentdict["st_mtime"] = content.st_mtime
                temp_contentdict["parent"] = remotepath
                remotepathlist.append(temp_contentdict)
                self.formatRemotepath(temp_contentdict["absname"])
            else:
                temp_contentdict["name"] = content.filename
                temp_contentdict["absname"] = remotepath + '/' + content.filename
                temp_contentdict["ftype"] = 2
                temp_contentdict["st_mtime"] = content.st_mtime
                temp_contentdict["parent"] = remotepath
                remotepathlist.append(temp_contentdict)

        return remotepathlist


    # 同步服务器指定监控目录的所有目录和文件
    def syncContent(self, remotepath):
        from modules.contentinfo.models import Contentinfo
        #初始化同步的目录
        self.initPathContent(remotepath)

        filelist = self.formatRemotepath(remotepath)
        for file in filelist:
            filestr = str(file["st_mtime"])
            try:
                content = Contentinfo.objects.get(absname=file["absname"], serverid=self)
            except:
                content = None
            if content:
                if content.newproperty == filestr:
                    content.changeflag = "0"
                else:
                    content.changeflag = "2"
                    content.oldproperty = content.newproperty
                content.newproperty = filestr
                content.writetime = datetime.datetime.now()
            else:
                content = Contentinfo(name=file["name"], absname=file["absname"], ftype=file["ftype"],
                                      superid=file["parent"],
                                      serverid=self, changeflag=1,
                                      oldproperty=0,
                                      newproperty=filestr, checkflag=1, writetime=datetime.datetime.now())
            content.save()

        return "syncContent==============="

    def __unicode__(self):
        return "%s  ( %s )" % (self.name, self.ip)

    class Meta:
        verbose_name = u"服务器信息"
        index_together = ["name"]  # 索引字段组合
        unique_together = (("ip", ),)


class ContentSetinfo(models.Model):
    """服务器和监控资源对应信息"""
    serverid = models.ForeignKey(Serverinfo, verbose_name=u"监控服务器", null=True, blank=True)
    absname = models.CharField(u"监控资源路径", max_length=300)
    user = models.ForeignKey(User, verbose_name=u"用户", null=True, blank=True)
    writetime = models.DateTimeField(u"更新时间", default=timezone.now, null=False, blank=False)

    def __unicode__(self):
        return self.serverid.name + self.absname

    class Meta:
        verbose_name = u"服务器和监控资源对应信息"
        unique_together = (("serverid", "absname", "user"  ),)

srmsproject/srms_win/mysite/modules/serverinfo/templates/contentset_edit.html
{% extends "base/base_edit.html" %}


{% block modules_js %}
    <script type="text/javascript">

{#        $('#id_absname').attr("readonly", "true");#}
{#        $('#id_absname').on('click', function () {#}
{#            select_content("#contenttreeview", "#myContentModal")#}
{##}
{##}
{#        });#}


    </script>
{% endblock %}


srmsproject/srms_win/mysite/modules/serverinfo/templates/contentset_list.html
{% extends "base/base.html" %}

{% block breadcrumb %}
    <li class="active">监控配置列表</li>
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="page-header">
                <div class="widget-box widget-color-blue2">
                    <div class="widget-header">
                        <i class="menu-icon fa fa-filter"></i>
                        <h5 class="widget-title">查询服务器</h5>

                        <div class="widget-toolbar">
                            <a href="#" data-action="collapse">
                                <i class="ace-icon fa fa-chevron-up"></i>
                            </a>
                        </div>

                        <div class="widget-toolbar">
                            <button class="btn btn-xs btn-info" onclick="$('#user_form').submit()" data-rel="tooltip"
                                    title="搜索服务器">
                                <i class="ace-icon glyphicon glyphicon-search bigger-120"></i>
                                搜索
                            </button>
                            <button class="btn btn-xs btn-info" data-rel="tooltip" title="新增配置"
                                    onclick="window.location.href='{% url "serverinfo:contentset_add" %}'">
                                <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                                新增
                            </button>
                        </div>
                    </div>
                    <div class="widget-body">
                        <form id="user_form" class="form-horizontal" method="get">
                            <div class="widget-main padding-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <p>
                                            <input type="text" id="dept_name" name="dept_name" placeholder="归属服务器搜索"
                                                   onclick="query_dept_param()" value="{{ dept_name }}" readonly/>
                                            <input type="hidden" id="dept_ids" name="dept_ids" value="{{ dept_ids }}"/>
                                            <input type="text" id="name" name="name" placeholder="名称搜索"
                                                   value="{{ first_name }}"/>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <div class="table-responsive">

                <table class="table table-striped table-hover dataTable">
                    <thead>
                    <tr>
                        <th class="center">
                            <label class="pos-rel">
                                <input type="checkbox" class="ace" name="check_all"/>
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th class="center">编号</th>
                        <th class="center">服务器名称</th>
                        <th class="center">服务器IP</th>
                        <th class="center">监控路径</th>
                        <th class="center">用户名称</th>
                        <th class="center">更新时间</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for contentset in contentset_list %}
                        <tr class="center">
                            <td>
                                <label class="pos-rel">
                                    <input type="checkbox" class="ace" name="db_id" value="{{ contentset.id }}"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>

                            <td>{{ contentset.id }}</td>
                            <td>{{ contentset.serverid.name }}</td>
                            <td>{{ contentset.serverid.ip }}</td>
                            <td>{{ contentset.absname }}</td>
                            <td>{{ contentset.user.username }}</td>
                            <td>{{ contentset.writetime }}</td>

                            <td>

                                <div>
                                    <button class="btn btn-minier btn-info"
                                            onclick="window.location.href='{% url "serverinfo:contentset_edit" pk=contentset.id %}'"
                                            title="编辑配置">
                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                    </button>
                                    <button class="btn btn-minier btn-danger"
                                            onclick="window.location.href='{% url "serverinfo:contentset_delete" pk=contentset.id %}'"
                                            title="删除配置">
                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                    </button>
                                </div>

                            </td>
                        </tr>
                    {% empty %}
                        <tr class="info">
                            <td colspan="25">抱歉，目前没有满足条件的信息。</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.span -->
        </div>
    </div><!-- /.row -->

    {% include  "base/paginator.html" %}

{% endblock %}

srmsproject/srms_win/mysite/modules/serverinfo/templates/serverinfo_chart.html
{% extends "base/base.html" %}

{% block breadcrumb %}
    <li class="active">监控服务器图表</li>
{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div>
                <ul class="ace-thumbnails clearfix">
                    {% for server in serverlist %}
                    <li>
                        <a href="/contentinfo/server/?serverid={{ server.id }}" target="_blank">

                        <img width="150" height="150" alt="150x150" src="/static/images/gallery/server.png"/>
                        </a>
                        <div width="150">名称：{{ server.name|truncatechars:16 }}</div>
                        <div width="150">I  P：{{ server.ip|truncatechars:16 }}</div>
                        <div width="150">时间：{{ server.synctime|date:"Y-m-d H:i"|truncatechars:16 }}</div>

                    </li>
                    {% empty %}
                        <div class="info">
                            <td colspan="25">抱歉，目前没有满足条件的服务器信息。</td>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div>
        <!-- /.col -->
    </div>



{% endblock %}
{% block js %}
    <script src="/static/js/jquery-ui.custom.js"></script>
{% endblock %}


{% block self_js %}

    <script type="text/javascript">


    </script>
{% endblock %}

srmsproject/srms_win/mysite/modules/serverinfo/templates/serverinfo_edit.html
{% extends "base/base_edit.html" %}


{% block modules_js %}
    <script type="text/javascript">

        $("#id_password").attr("type","password");


    </script>
{% endblock %}


srmsproject/srms_win/mysite/modules/serverinfo/templates/serverinfo_list.html
{% extends "base/base.html" %}

{% block breadcrumb %}
    <li class="active">服务器列表</li>
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="page-header">
                <div class="widget-box widget-color-blue2">
                    <div class="widget-header">
                        <i class="menu-icon fa fa-filter"></i>
                        <h5 class="widget-title">查询服务器</h5>

                        <div class="widget-toolbar">
                            <a href="#" data-action="collapse">
                                <i class="ace-icon fa fa-chevron-up"></i>
                            </a>
                        </div>

                        <div class="widget-toolbar">
                            <button class="btn btn-xs btn-info" onclick="$('#user_form').submit()" data-rel="tooltip"
                                    title="搜索服务器">
                                <i class="ace-icon glyphicon glyphicon-search bigger-120"></i>
                                搜索
                            </button>
                            <button class="btn btn-xs btn-info" data-rel="tooltip" title="新增服务器"
                                    onclick="window.location.href='{% url "serverinfo:serverinfo_add" %}'">
                                <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                                新增
                            </button>
                        </div>
                    </div>
                    <div class="widget-body">
                        <form id="user_form" class="form-horizontal" method="get">
                            <div class="widget-main padding-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <p>
                                            <input type="text" id="dept_name" name="dept_name" placeholder="归属服务器搜索"
                                                   onclick="query_dept_param()" value="{{ dept_name }}" readonly/>
                                            <input type="hidden" id="dept_ids" name="dept_ids" value="{{ dept_ids }}"/>
                                            <input type="text" id="name" name="name" placeholder="名称搜索"
                                                   value="{{ first_name }}"/>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <div class="table-responsive">

                <table class="table table-striped table-hover dataTable">
                    <thead>
                    <tr>
                        <th class="center">
                            <label class="pos-rel">
                                <input type="checkbox" class="ace" name="check_all"/>
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th class="center">服务器编号</th>
                        <th class="center">服务器名称</th>
                        <th class="center">IP</th>
                        <th class="center">端口</th>
                        <th class="center">用户名称</th>
                        <th class="center">监控</th>
                        <th class="center">更新时间</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for serverinfo in serverinfo_list %}
                        <tr class="center">
                            <td>
                                <label class="pos-rel">
                                    <input type="checkbox" class="ace" name="db_id" value="{{ serverinfo.id }}"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>

                            <td>{{ serverinfo.id }}</td>
                            <td>{{ serverinfo.name }}</td>
                            <td>{{ serverinfo.ip }}</td>
                            <td>{{ serverinfo.port }}</td>
                            <td>{{ serverinfo.username }}</td>
                            <td>{{ serverinfo.checkflag|yesno:" "  }}</td>
                            <td>{{ serverinfo.writetime }}</td>

                            <td>

                                <div>
                                    <button class="btn btn-minier btn-info"
                                            onclick="window.location.href='{% url "serverinfo:serverinfo_edit" pk=serverinfo.id %}'" title="编辑服务器">
                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                    </button>
                                    <button class="btn btn-minier "
                                            onclick="window.location.href='{% url "serverinfo:serverinfo_conn" pk=serverinfo.id %}'" title="连接测试">
                                        <i class="ace-icon fa  fa-circle-o  bigger-120"></i>
                                    </button>
                                    <button class="btn btn-minier btn-purple"
                                            onclick="window.location.href='{% url "serverinfo:serverinfo_init" pk=serverinfo.id %}'" title="初始化数据">
                                        <i class="ace-icon fa fa-download bigger-120"></i>
                                    </button>
                                    <button class="btn btn-minier btn-success"
                                            onclick="window.location.href='{% url "serverinfo:serverinfo_sync" pk=serverinfo.id %}'" title="同步数据">
                                        <i class="ace-icon fa fa-exchange bigger-120"></i>
                                    </button>
                                    <button class="btn btn-minier btn-danger"
                                            onclick="window.location.href='{% url "serverinfo:serverinfo_delete" pk=serverinfo.id %}'" title="删除服务器">
                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                    </button>
                                </div>

                            </td>
                        </tr>
                    {% empty %}
                        <tr class="info">
                            <td colspan="25">抱歉，目前没有满足条件的资源信息。</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.span -->
        </div>
    </div><!-- /.row -->

    {% include  "base/paginator.html" %}

{% endblock %}