srmsproject/srms_win/mysite/modules/systeminfo/urls.py
# coding=utf-8

from django.conf.urls import url
from modules.systeminfo import views

urlpatterns = [
    url(r'^param/', views.SysteminfoParam.as_view(), name="systeminfo_param"),
    url(r'^paramupdate/', views.SysteminfoParamUpdateView.as_view(), name="systeminfo_paramupdate"),
    url(r'^list/', views.SysteminfoList.as_view(), name="systeminfo_list"),
    url(r'^config/', views.SystemConfigView.as_view(), name="systeminfo_config"),
    url(r'^update/', views.SystemUpdateView.as_view(), name="systeminfo_update"),
]

srmsproject/srms_win/mysite/mysite/urls.py
# coding=utf-8
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.static import serve
from django.http import HttpResponseRedirect
from django.contrib import admin

from mysite import settings
from modules.common.views import SidebarMenusList


handler500 = "modules.common.views.redirect_500_error"
handler404 = "modules.common..views.redirect_404_error"
handler403 = "modules.common..views.redirect_403_error"
handler400 = "modules.common..views.redirect_400_error"


def index(request):
    response = HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
    return response


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', admin.site.urls),
    url(r'^$', index),
    url(r'^homepage/', include('modules.common.urls', namespace='homepage')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_PATH, }),
    url(r'^contentinfo/', include('modules.contentinfo.urls', namespace='contentinfo')),
    url(r'^serverinfo/', include('modules.serverinfo.urls', namespace='serverinfo')),
    url(r'^userinfo/', include('modules.userinfo.urls', namespace='userinfo')),
    url(r'^userlog/', include('modules.userlog.urls', namespace='userlog')),
    url(r'^systeminfo/', include('modules.systeminfo.urls', namespace='systeminfo')),
    url(r'^getmenubyuser/$', SidebarMenusList.as_view(), name='getmenubyuser'),
]


# 上传文件目录
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srmsproject/srms_win/mysite/modules/systeminfo/models.py
# coding=utf-8
from django.db import models
from django.core.cache import cache
import traceback

SYSVERSION = 1


class Systeminfo(models.Model):
    PARAMTYPECHOICE = (
        ('1', u'常规'),
        ('2', u'Email'),
        ('3', u'定时任务'),
    )

    param_name = models.CharField(u"参数名", max_length=100)
    param_value = models.CharField(u"参数值", max_length=100)
    param_display = models.CharField(u"参数描述", max_length=100)
    param_type = models.CharField(u"参数类型", max_length=2, choices=PARAMTYPECHOICE)

    def __unicode__(self):
        return self.param_name + self.param_value

    class Meta:
        verbose_name = u"系统设置"
        index_together = ["id", "param_name"]  # 索引字段组合
        permissions = (
            ("browse_systeminfo", u"授权浏览 系统设置"),
        )


    @staticmethod
    def update_system_cache():
        global SYSVERSION
        SYSVERSION += 1

    @staticmethod
    def get_param_value(param_name, param_type='1'):
        global SYSVERSION
        try:
            param_value = cache.get("sys_config_%s_%s_%s" % (SYSVERSION, param_type, param_name))
            if param_value:
                return param_value
            systeminfolist = Systeminfo.objects.filter(param_name=param_name, param_type=param_type)
            if systeminfolist:
                systeminfo = systeminfolist[0]
                param_value = systeminfo.param_value
                cache.set("sys_config_%s_%s_%s" % (SYSVERSION, param_type, param_name), param_value)
            else:
                param_value = ""
            return param_value
        except:
            traceback.print_exc()
            return ""

    @staticmethod
    def get_param(param_name):
        global SYSVERSION
        try:
            result = {param_name: ""}
            systeminfo = cache.get("sys_config_%s_%s" % (param_name, SYSVERSION))
            if systeminfo:
                return systeminfo
            systeminfo = Systeminfo.objects.filter(param_name=param_name)
            if systeminfo.exists():
                systeminfo_s = systeminfo[0]
                result = {systeminfo_s.param_name: systeminfo_s.param_value}
                cache.set("sys_config_%s_%s" % (param_name, SYSVERSION), result)
            return result
        except:
            traceback.print_exc()
            return {param_name: ""}

    def save(self, *args, **kwargs):
        global DEPTVERSION
        try:
            self.update_system_cache()
            super(Systeminfo, self).save(*args, **kwargs)
        except:
            traceback.print_exc()

srmsproject/srms_win/mysite/modules/systeminfo/views.py
# coding=utf-8

from mysite import settings
import traceback
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render_to_response
from django.apps import AppConfig
from django.template import RequestContext
from django.views.generic import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.db.models.signals import post_migrate
from django.dispatch import receiver
from modules.systeminfo.models import Systeminfo

from django.shortcuts import render
from modules.common.utils import *
from django.contrib import messages
from django.http import HttpResponse


class SysteminfoInit(LoginRequiredMixin, View):
    context_object_name = "systeminfo_list"
    template_name = "systeminfo_list.html"
    allow_empty = True
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        name = "QiaoTest"
        ip = "192.168.174.128"
        port = 22
        username = "redhat"
        password = "redhat"
        try:
            server = Systeminfo(name, ip, port, username, password)
            server.save()
            # server.initContent()
            return redirect(reverse('systeminfo:systeminfo_list'))
        except:
            traceback.print_exc()


class SysteminfoList(LoginRequiredMixin, ListView):
    context_object_name = "systeminfo_list"
    template_name = "systeminfo_list.html"
    allow_empty = True
    paginate_by = 10

    def get_queryset(self):
        return Systeminfo.objects.all()


class SysteminfoParam(LoginRequiredMixin, ListView):
    context_object_name = "param_list"
    template_name = "systeminfo_param.html"
    allow_empty = True
    paginate_by = 10

    def get_queryset(self):
        return Systeminfo.objects.all()


class SysteminfoCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "systeminfo_edit.html"
    success_url = "/systeminfo/list"
    model = Systeminfo
    fields = "__all__"
    success_message = u"%(name)s 成功创建"

    def form_valid(self, form):
        try:
            name = self.request.POST.get("name", "")
            ip = self.request.POST.get("ip", "")
            port = self.request.POST.get("port", "")
            username = self.request.POST.get("username", "")
            password = self.request.POST.get("password", "")
            writetime = self.request.POST.get("writetime", "")

            form.instance.name = name
            form.instance.ip = ip
            form.instance.port = port
            form.instance.username = username
            form.instance.password = password
            form.instance.writetime = writetime
            return super(SysteminfoCreate, self).form_valid(form)
        except:
            traceback.print_exc()


class SysteminfoUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "systeminfo_edit.html"
    success_url = "/systeminfo/list"
    model = Systeminfo
    fields = "__all__"
    success_message = u"%(name)s 修改成功"


    def get_context_data(self, **kwargs):
        context = super(SysteminfoUpdate, self).get_context_data(**kwargs)
        context["form_content"] = u"编辑信息"
        return context


class SysteminfoDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = "base/confirm_delete.html"
    success_url = "/systeminfo/list"
    model = Systeminfo
    fields = "__all__"
    success_message = u"%(name)s 删除成功"


class SystemConfigView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:

            import platform
            import uuid


            system = " Microsoft Windows 7"
            mac = "00-50-56-C0-00-08"
            ip = "127.0.0.1"
            cpu = "Intel64 Family 6 Model 2277 Mhz"
            memory = "8.00 GB"
            language = " Python27"
            service = "Apache"
            database = "MySQL"
            nodenumber = "300"
            version = "VERSION 1.0.1"

            system = platform.platform()
            cpu = platform.processor()
            mac = uuid.uuid1().hex[-12:].lower()
            database = settings.DATABASE_ENGINE
            language = settings.LANGUAGE
            nodenumber = settings.NODENUMBER
            version = settings.VERSION

            systeminfo = {"system": system, "mac": mac, "ip": ip, "cpu": cpu, "memory": memory, "language": language,
                          "service": service, "database": database, "nodenumber": nodenumber, "version": version}

            template_name = "systeminfo_config.html"
            return render_to_response(template_name,
                                      {"systeminfo": systeminfo})
        except:
            traceback.print_exc()


class SystemUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            param_list = Systeminfo.objects.all()
            template_name = "systeminfo_update.html"
            result_dict = {}
            return render(request, template_name, result_dict)
        except:
            traceback.print_exc()

    def post(self, request, *args, **kwargs):
        try:
            template_name = "systeminfo_update.html"
            result_dict = {}

            updatefile = request.POST.get("updatefile", "")
            fs = request.FILES
            if fs.has_key("updatefile"):
                f = fs["updatefile"]
                requestfname = "updatefile"
                fname = "%s%s%s" % (settings.ADDITION_FILE_ROOT, 'upload/system/update/', f)

                uploadfile(request, requestfname, fname)

                updatesys(request)

                messages.add_message(request, messages.SUCCESS, "升级成功！")

            else:
                messages.add_message(request, messages.ERROR, "升级文件不正确，请检查后升级！")

            return render(request, template_name, result_dict)
        except:
            traceback.print_exc()


class SysteminfoParamUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            param_list = Systeminfo.objects.all()
            template_name = "systeminfo_param.html"
            result_dict = {"param_list": param_list}
            return render(request, template_name, result_dict)
        except:
            traceback.print_exc()

    def post(self, request, *args, **kwargs):
        template_name = "systeminfo_param.html"
        try:
            result_dict = {}
            param_name = request.POST.get("name", "")
            param_value = request.POST.get("newvalue", "")
            try:
                Systeminfo.objects.filter(param_name=param_name).update(param_value=param_value)
                Systeminfo.update_system_cache()
                result_dict["msg"] = "设置成功!"
            except:
                result_dict["msg"] = "设置失败！"

            return HttpResponse(json.dumps(result_dict), content_type="application/json")
        except:
            traceback.print_exc()

srmsproject/srms_win/mysite/modules/systeminfo/templates/systeminfo_config.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/jquery-ui.custom.css"/>
    <link rel="stylesheet" href="/static/css/bootstrap-editable.css"/>
{% endblock %}

{% block breadcrumb %}
    <li><a href="#">系统相关</a></li>
    <li class="active">系统信息</li>
{% endblock %}

{% block page-content %}

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="space-6"></div>

            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <!-- #section:pages/invoice -->
                    <div class="widget-box transparent">
                        <div class="widget-header widget-header-large">
                            <h3 class="widget-title grey lighter">
                                <i class="ace-icon fa fa-leaf green"></i>
                                系统环境
                            </h3>

                            <!-- #section:pages/invoice.info -->
                            <div class="widget-toolbar no-border invoice-info">
                                <span class="invoice-info-label">电话:</span>
                                <span class="red">#400-8888</span>

                                <br/>
                                <span class="invoice-info-label">邮件:</span>
                                <span class="blue">www@www.com</span>
                            </div>

                            <div class="widget-toolbar hidden-480">
                                <a href="#">
                                    <i class="ace-icon fa fa-print"></i>
                                </a>
                            </div>

                            <!-- /section:pages/invoice.info -->
                        </div>

                        <div class="widget-body">
                            <div class="widget-main padding-24">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="row">
                                            <div class="col-xs-11 label label-lg label-info arrowed-in arrowed-right">
                                                <b>系统信息</b>
                                            </div>
                                        </div>

                                        <div>
                                            <ul class="list-unstyled spaced">

                                                <li>
                                                    <i class="ace-icon fa fa-caret-right blue"></i>
                                                    开发语言:
                                                    <b class="blue">{{ systeminfo.language }}</b>
                                                </li>

                                                <li>
                                                    <i class="ace-icon fa fa-caret-right blue"></i>
                                                    WEB服务:
                                                    <b class="blue">{{ systeminfo.service }}</b>
                                                </li>

                                                <li>
                                                    <i class="ace-icon fa fa-caret-right blue"></i>
                                                    数据库:
                                                    <b class="blue">{{ systeminfo.database }}</b>
                                                </li>
                                                <li>
                                                    <i class="ace-icon fa fa-caret-right blue"></i>
                                                    节点数:
                                                    <b class="blue">{{ systeminfo.nodenumber }}</b>
                                                </li>

                                                <li>
                                                    <i class="ace-icon fa fa-caret-right blue"></i>
                                                    软件版本:
                                                    <b class="blue">{{ systeminfo.version }}</b>
                                                </li>


                                            </ul>
                                        </div>
                                    </div>
                                    <!-- /.col -->

                                    <div class="col-sm-6">
                                        <div class="row">
                                            <div class="col-xs-11 label label-lg label-success arrowed-in arrowed-right">
                                                <b>服务器信息</b>
                                            </div>
                                        </div>

                                        <div>
                                            <ul class="list-unstyled  spaced">
                                                <li>
                                                    <i class="ace-icon fa fa-caret-right green"></i>
                                                    操作系统:
                                                    <b class="green">{{ systeminfo.system }}</b>
                                                </li>
                                                <li>
                                                    <i class="ace-icon fa fa-caret-right green"></i>
                                                    IP地址:
                                                    <b class="green">{{ systeminfo.ip }}</b>
                                                </li>
                                                <li>
                                                    <i class="ace-icon fa fa-caret-right green"></i>
                                                    MAC地址:
                                                    <b class="green">{{ systeminfo.mac }}</b>
                                                </li>
                                                <li>
                                                    <i class="ace-icon fa fa-caret-right green"></i>
                                                    CPU:
                                                    <b class="green">{{ systeminfo.cpu }}</b>
                                                </li>
                                                <li>
                                                    <i class="ace-icon fa fa-caret-right green"></i>
                                                    内存:
                                                    <b class="green">{{ systeminfo.memory }}</b>
                                                </li>


                                            </ul>
                                        </div>
                                    </div>
                                    <!-- /.col -->
                                </div>
                                <!-- /.row -->

                                <div class="space"></div>


                                <div class="hr hr8 hr-double hr-dotted"></div>


                                <div class="space-6"></div>
                                <div class="well">
                                    {{ site_name }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- /section:pages/invoice -->
                </div>
            </div>

            <!-- PAGE CONTENT ENDS -->
        </div>
        <!-- /.col -->
    </div><!-- /.row -->




{% endblock %}

{% block js %}
    <!--[if lte IE 8]>
		  <script src="/static/js/excanvas.js"></script>
		<![endif]-->
    <script src="/static/js/jquery-ui.custom.js"></script>
    <script src="/static/js/jquery.ui.touch-punch.js"></script>
    <script src="/static/js/jquery.hotkeys.js"></script>
    <script src="/static/js/bootstrap-wysiwyg.js"></script>
    <script src="/static/js/fuelux/fuelux.spinner.js"></script>
    <script src="/static/js/x-editable/bootstrap-editable.js"></script>
    <script src="/static/js/x-editable/ace-editable.js"></script>
    <script src="/static/js/jquery.maskedinput.js"></script>
    <script src="/static/customjs/custom_base.js"></script>
{% endblock %}


srmsproject/srms_win/mysite/modules/systeminfo/templates/systeminfo_list.html
{% extends "base/base.html" %}

{% block css %}

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="/static/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/css/font-awesome.css"/>

    <!-- page specific plugin styles -->
    <link rel="stylesheet" href="/static/css/jquery-ui.custom.css"/>
    <link rel="stylesheet" href="/static/css/jquery.gritter.css"/>
    <link rel="stylesheet" href="/static/css/select2.css"/>
    <link rel="stylesheet" href="/static/css/bootstrap-datepicker3.css"/>
    <link rel="stylesheet" href="/static/css/bootstrap-editable.css"/>

    <!-- text fonts -->
    <link rel="stylesheet" href="/static/css/ace-fonts.css"/>

    <!-- ace styles -->
    <link rel="stylesheet" href="/static/css/ace.css" class="ace-main-stylesheet" id="main-ace-style"/>

    <!--[if lte IE 9]>
			<link rel="stylesheet" href="/static/css/ace-part2.css" class="ace-main-stylesheet" />
		<![endif]-->

    <!--[if lte IE 9]>
		  <link rel="stylesheet" href="/static/css/ace-ie.css" />
		<![endif]-->

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="/static/js/ace-extra.js"></script>

{% endblock %}

{% block page-content %}

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="tabbable">
                <!-- #section:pages/faq -->
                <ul class="nav nav-tabs padding-18 tab-size-bigger" id="myTab">
                    <li class="active">
                        <a data-toggle="tab" href="#faq-tab-1">
                            <i class="blue ace-icon fa fa-cog bigger-120"></i>
                            设置
                        </a>
                    </li>

                    <li>
                        <a data-toggle="tab" href="#faq-tab-2">
                            <i class="red ace-icon fa fa-envelope bigger-120"></i>
                            Email
                        </a>
                    </li>

                    <li>
                        <a data-toggle="tab" href="#faq-tab-3">
                            <i class="orange ace-icon fa fa-clock-o bigger-120"></i>
                            定时任务
                        </a>
                    </li>

                </ul>

                <!-- /section:pages/faq -->
                <div class="tab-content no-border padding-24">
                    <div id="faq-tab-1" class="tab-pane fade in active">
                        <h4 class="blue">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            设置系统常用属性
                        </h4>

                        <div class="space-8"></div>

                        <div class="profile-user-info profile-user-info-striped">
                            {% for systeminfo in systeminfo_list %}
                                {% ifequal systeminfo.param_type "1" %}

                                    <div class="profile-info-row">
                                        <div class="profile-info-name">{{ systeminfo.param_display }}</div>

                                        <div class="profile-info-value">
                                            <span class="editable"
                                                  id="{{ systeminfo.param_name }}">{{ systeminfo.param_value }}</span>
                                        </div>
                                    </div>
                                {% endifequal %}
                            {% endfor %}
                        </div>
                    </div>

                    <div id="faq-tab-2" class="tab-pane fade">
                        <h4 class="blue">
                            <i class="red ace-icon fa fa-envelope bigger-110"></i>
                            Email权限设置
                        </h4>

                        <div class="space-8"></div>

                        <div class="profile-user-info profile-user-info-striped">
                            {% for systeminfo in param_list %}
                                {% ifequal systeminfo.param_type "2" %}
                                    <div class="profile-info-row">
                                        <div class="profile-info-name">{{ systeminfo.param_display }}</div>

                                        <div class="profile-info-value">
                                            <span class="editable" id="{{ systeminfo.param_name }}">
                                                {{ systeminfo.param_value }}
                                            </span>
                                        </div>
                                    </div>
                                {% endifequal %}
                            {% endfor %}
                        </div>
                    </div>

                    <div id="faq-tab-3" class="tab-pane fade">
                        <h4 class="blue">
                            <i class="orange ace-icon fa fa-clock-o bigger-110"></i>
                            定时任务设置
                        </h4>

                        <div class="space-8"></div>

                        <div class="profile-user-info profile-user-info-striped">
                            {% for systeminfo in param_list %}
                                {% ifequal systeminfo.param_type "3" %}
                                    <div class="profile-info-row">
                                        <div class="profile-info-name">{{ systeminfo.param_display }}</div>

                                        <div class="profile-info-value">
                                            <span class="editable"
                                                  id="{{ systeminfo.param_name }}">{{ systeminfo.param_value }}</span>
                                        </div>
                                    </div>
                                {% endifequal %}
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>

            <!-- PAGE CONTENT ENDS -->
        </div>
        <!-- /.col -->
    </div><!-- /.row -->


{% endblock %}


{% block js %}


    <!-- basic scripts -->

    <!--[if !IE]> -->
    <script type="text/javascript">
        window.jQuery || document.write("<script src='/static/js/jquery.js'>" + "<" + "/script>");
    </script>

    <!-- <![endif]-->


    <script src="/static/js/bootstrap.js"></script>

    <!-- page specific plugin scripts -->

    <!--[if lte IE 8]>
		  <script src="/static/js/excanvas.js"></script>
		<![endif]-->
    <script src="/static/js/jquery-ui.custom.js"></script>
    <script src="/static/js/jquery.ui.touch-punch.js"></script>
    <script src="/static/js/jquery.gritter.js"></script>
    <script src="/static/js/bootbox.js"></script>
    <script src="/static/js/jquery.easypiechart.js"></script>
    <script src="/static/js/date-time/bootstrap-datepicker.js"></script>
    <script src="/static/js/jquery.hotkeys.js"></script>
    <script src="/static/js/bootstrap-wysiwyg.js"></script>
    <script src="/static/js/select2.js"></script>
    <script src="/static/js/fuelux/fuelux.spinner.js"></script>
    <script src="/static/js/x-editable/bootstrap-editable.js"></script>
    <script src="/static/js/x-editable/ace-editable.js"></script>
    <script src="/static/js/jquery.maskedinput.js"></script>
    <script src="/static/customjs/custom_base.js"></script>



    <!-- inline scripts related to this page -->
    <script type="text/javascript">
        jQuery(function ($) {

            //editables on first profile page
            $.fn.editable.defaults.mode = 'inline';
            $.fn.editableform.loading = "<div class='editableform-loading'><i class='ace-icon fa fa-spinner fa-spin fa-2x light-blue'></i></div>";
            $.fn.editableform.buttons = '<button type="submit" class="btn btn-info editable-submit"><i class="ace-icon fa fa-check"></i></button>' +
                    '<button type="button" class="btn editable-cancel"><i class="ace-icon fa fa-times"></i></button>';

            //editables

            //text editable

            $('#site_name')
                    .editable({
                        type: 'text',
                        name: 'site_name',
                        success: function (response, newValue) {
                            var param_dict = {};
                            param_dict["name"] = "site_name";
                            param_dict["newvalue"] = newValue;
                            change_system_config(param_dict)
                        }
                    });

            $('#company_name')
                    .editable({
                        type: 'text',
                        name: 'company_name',
                        success: function (response, newValue) {
                            var param_dict = {};
                            param_dict["name"] = "company_name";
                            param_dict["newvalue"] = newValue;
                            change_system_config(param_dict)
                        }
                    });

            $('#chartspeed').editable({
                type: 'spinner',
                name: 'age',
                spinner: {
                    min: 1,
                    max: 10,
                    step: 1,
                    on_sides: true
                    //,nativeUI: true//if true and browser support input[type=number], native browser control will be used
                },

                success: function (response, newValue) {
                    var param_dict = {};
                    param_dict["name"] = "chartspeed";
                    param_dict["newvalue"] = newValue;
                    change_system_config(param_dict)
                }


            });
        });


        function change_system_config(param_dict) {
            alert(param_dict)
            var change_url = "{% url "systeminfo:systeminfo_paramupdate" %}";
            custom_ajax_post(change_url, param_dict)
        }

    </script>

{% endblock %}